### ISSUE TITLE
docker-intro.zip file is missing

### ISSUE THREAD

**Issue by askorikov** [esciencecenter-digital-skills/2022-04-06-ds-docker#1]
First of all, thanks for organizing the workshop! :) Right now it seems that the `docker-intro.zip` file is missing form the `files` folder of the repository and the link to it on the index page is broken (`{{ page.root }}` field doesn't seem to have been resolved).

**Comment by askorikov** [comment]
I've managed to find the `docker-intro.zip` file in the correct repository (`https://github.com/esciencecenter-digital-skills/docker-introduction`) but the link issue problem remains (and there's another unresolved filed in the same paragraph: `[docker-introduction GitHub repository][docker-introduction repository]`).

**Comment by dsmits** [comment]
The zipfile is not really necessary for the workshop. I thought I removed it from the instructions. I'll make sure it is gone.

**Comment by askorikov** [comment]
Ah, okay then. Thanks!
